# Generated by Django 5.2.8 on 2025-11-08 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('read', 'Reading Exam'), ('write', 'Writing Exam')], max_length=20)),
                ('content', models.JSONField(help_text='Structured exam content as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('read', 'Read Exam'), ('write', 'Write Exam'), ('read_review', 'Read Review'), ('write_review', 'Write Review')], max_length=20, unique=True)),
                ('num_chars', models.IntegerField(default=10)),
                ('lessons', models.CharField(default='1-10', max_length=50)),
                ('score_filter', models.IntegerField(blank=True, null=True)),
                ('days_filter', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('header_text', models.CharField(default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exam_settings',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cloze', 'Cloze Test'), ('chars', 'Character Study'), ('failed', 'Failed Words Review'), ('review', 'Exam/Review Session'), ('words', 'Find Words Puzzle')], max_length=20)),
                ('content', models.JSONField(help_text='Structured study content as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.IntegerField(help_text='The lesson number the character belongs to')),
                ('hanzi', models.CharField(help_text='The Chinese character', max_length=10, unique=True)),
            ],
            options={
                'db_table': 'words',
                'ordering': ['lesson', 'hanzi'],
            },
        ),
        migrations.CreateModel(
            name='WordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='A multi-character Chinese word', max_length=50, unique=True)),
                ('score', models.FloatField(default=0.5, help_text='A score indicating how common the word is (0.0 to 1.0)')),
            ],
            options={
                'db_table': 'word_entries',
                'ordering': ['-score', 'word'],
            },
        ),
        migrations.CreateModel(
            name='StudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('read', 'Read Exam'), ('write', 'Write Exam'), ('readstudy', 'Read Study'), ('writestudy', 'Write Study')], max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('study_date', models.DateField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_logs', to='studies.word')),
            ],
            options={
                'db_table': 'study_logs',
                'ordering': ['study_date'],
            },
        ),
    ]
