# Generated by Django 5.2.8 on 2025-11-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_num', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('is_learned', models.BooleanField(default=False)),
                ('characters', models.TextField()),
            ],
            options={
                'ordering': ['lesson_num'],
            },
        ),
    ]
