# Generated by Django 5.2.8 on 2025-11-09 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsettings',
            name='lessons',
        ),
    ]
