# Generated by Django 5.2.8 on 2025-11-26 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_remove_examsettings_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0, help_text='Order of the book in the curriculum')),
            ],
            options={
                'db_table': 'books',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['book__order', 'lesson_num']},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_num',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='studies.book'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('book', 'lesson_num')},
        ),
    ]
