# Generated by Django 5.2.8 on 2025-11-26 23:26

from django.db import migrations



def assign_default_book(apps, schema_editor):
    Book = apps.get_model('studies', 'Book')
    Lesson = apps.get_model('studies', 'Lesson')
    
    # Create default book
    default_book, created = Book.objects.get_or_create(
        title='Book 1',
        defaults={'description': 'Default book for existing lessons', 'order': 1}
    )
    
    # Assign all existing lessons to the default book
    Lesson.objects.filter(book__isnull=True).update(book=default_book)

class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_book_alter_lesson_options_lesson_id_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_default_book),
    ]
