# Generated by Django 5.2.8 on 2025-11-26 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_assign_default_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='studies.book'),
        ),
    ]
