# Generated by Django 5.2.8 on 2025-11-28 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_alter_lesson_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['hanzi']},
        ),
        migrations.RemoveField(
            model_name='word',
            name='lesson',
        ),
    ]
