# Generated by Django 6.0 on 2026-01-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_remove_word_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsettings',
            name='include_hard_mode',
            field=models.BooleanField(default=False),
        ),
    ]
